### ISSUE TITLE
5.1.5 - exc_bad_access on dictionaryRepresenation

### ISSUE THREAD

**Issue by zirinisp** [orlandos-nl/BSON#36]
I haven't look into this bug further, but it was not there in the past. I am getting the following:

<img width="1233" alt="screen shot 2017-10-24 at 08 38 58" src="https://user-images.githubusercontent.com/2939569/31930385-7b812298-b897-11e7-9cfa-066d47ff99c2.png">
<img width="466" alt="screen shot 2017-10-24 at 08 42 26" src="https://user-images.githubusercontent.com/2939569/31930386-7b9ad8fa-b897-11e7-9ab9-1e28ac5ce084.png">

I hope the screenshots help

**Comment by Joannis** [comment]
Thanks for the report, I don't really know what could cause this though (not from the screenshots). We did fix a bug that would crash once roughly every (3?) million runs, so that might be the bug. It was fixed 2-3 versions ago. So a few versions after 5.1.5. But other than that I can't do much with this bug now.

Thanks for the report though :) I'll keep an eye out, and thanks for the screenshots.

**Comment by zirinisp** [comment]
I know the screenshots are not very helpful.

Tried to get the last version, but there were some changes and I got error all over the place.

I will stick with 5.1.4 for the moment. With the release of iOS 11 all I have been doing is trying to make things work again.

**Comment by Joannis** [comment]
What kind of errors did you get?

**Comment by zirinisp** [comment]
You have refactored some functions and they have different names. So it would not compile.

**Comment by Joannis** [comment]
Which functions are those? I might have merged the wrong code into master.
