### ISSUE TITLE
Cannot load module

### ISSUE THREAD

**Issue by d0hnj0e** [orlandos-nl/BSON#61]
When trying to build, I always receive the error `<unknown>:0: error: cannot load module 'BSON' as 'bson'`.

Could one kindly assist? Any help much appreciated!

**Comment by Joannis** [comment]
@d0hnj0e Does this error occur in your codebase, or MongoKitten's? If it's your codebase, make sure that BSON is spelled exactly like that, with only capital letters. When importing MongoKitten, BSON is imported as part of the MongoKitten dependency. It's an exported dependency, because BSON is used so commonly throughout MongoKitten.
